trunk/SicaCard/src/br/com/sicacard/model/entity/Cliente.java
package br.com.sicacard.model.entity;

import java.util.List;

/**
 * Cliente.java
 *
 * @author nayalison <br />
 *     		nayalison@gmail.com
 *
 * @since 15/04/2012
 * @version 1.0
 */
public class Cliente implements GenericEntity{

	private static final long serialVersionUID = -2908915722311271177L;
	private Long codCliente;
	private String endereco;
	private String telefone;
	private DadosBancario dadosBancario;
	private List<Dependente> dependentes;


	/**
	 * Default constructor.
	 */
	public Cliente() {
		super();
	}

	/**
	 * Get the codCliente
	 * @return <code>Long</code>
	 */
	public final Long getCodCliente() {
		return codCliente;
	}

	/**
	 * Set the codCliente
	 * @param codCliente the <code>Long</code>
	 */
	public final void setCodCliente(Long codCliente) {
		this.codCliente = codCliente;
	}

	/**
	 * Get the endereco
	 * @return <code>String</code>
	 */
	public final String getEndereco() {
		return endereco;
	}

	/**
	 * Set the endereco
	 * @param endereco the <code>String</code>
	 */
	public final void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	/**
	 * Get the telefone
	 * @return <code>String</code>
	 */
	public final String getTelefone() {
		return telefone;
	}

	/**
	 * Set the telefone
	 * @param telefone the <code>String</code>
	 */
	public final void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	/**
	 * Get the dadosBancario
	 * @return <code>DadosBancario</code>
	 */
	public final DadosBancario getDadosBancario() {
		return dadosBancario;
	}

	/**
	 * Set the dadosBancario
	 * @param dadosBancario the <code>DadosBancario</code>
	 */
	public final void setDadosBancario(DadosBancario dadosBancario) {
		this.dadosBancario = dadosBancario;
	}

	/**
	 * Get the dependentes
	 * @return <code>List<Dependente></code>
	 */
	public final List<Dependente> getDependentes() {
		return dependentes;
	}

	/**
	 * Set the dependentes
	 * @param dependentes the <code>List<Dependente></code>
	 */
	public final void setDependentes(List<Dependente> dependentes) {
		this.dependentes = dependentes;
	}
	
	/**
	 * Método responsável por clonar os dados de um cliente
	 * 
	 * @param cliente {@link Cliente}
	 */
	public void clonar(Cliente cliente) {
		this.codCliente = cliente.getCodCliente();
		this.dadosBancario = cliente.getDadosBancario();
		this.dependentes = cliente.getDependentes();
		this.endereco = cliente.getEndereco();
		this.telefone = cliente.getTelefone();
	}

}

trunk/SicaCard/src/br/com/sicacard/model/entity/Posto.java
package br.com.sicacard.model.entity;


/**
 * Posto.java
 *
 * @author nayalison <br />
 *     		nayalison@gmail.com
 *
 * @since 15/04/2012
 * @version 1.0
 */
public class Posto implements GenericEntity{

	private static final long serialVersionUID = 5470928451346777293L;
	private Long cnpj;
	private String nomeFantasia;
	private String razaoSocial;
	private String telefone;
	private DadosBancario dadosBancario;


	/**
	 * Default constructor.
	 */
	public Posto() {
		super();
	}

	/**
	 * Get the nomeFantasia
	 * @return <code>String</code>
	 */
	public final String getNomeFantasia() {
		return nomeFantasia;
	}

	/**
	 * Set the nomeFantasia
	 * @param nomeFantasia the <code>String</code>
	 */
	public final void setNomeFantasia(String nomeFantasia) {
		this.nomeFantasia = nomeFantasia;
	}

	/**
	 * Get the razaoSocial
	 * @return <code>String</code>
	 */
	public final String getRazaoSocial() {
		return razaoSocial;
	}


	/**
	 * Set the razaoSocial
	 * @param razaoSocial the <code>String</code>
	 */
	public final void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	/**
	 * Get the cnpj
	 * @return <code>Long</code>
	 */
	public final Long getCnpj() {
		return cnpj;
	}

	/**
	 * Set the cnpj
	 * @param cnpj the <code>Long</code>
	 */
	public final void setCnpj(Long cnpj) {
		this.cnpj = cnpj;
	}

	/**
	 * Get the telefone
	 * @return <code>String</code>
	 */
	public final String getTelefone() {
		return telefone;
	}

	/**
	 * Set the telefone
	 * @param telefone the <code>String</code>
	 */
	public final void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	/**
	 * Get the dadosBancario
	 * @return <code>DadosBancario</code>
	 */
	public final DadosBancario getDadosBancario() {
		return dadosBancario;
	}

	/**
	 * Set the dadosBancario
	 * @param dadosBancario the <code>DadosBancario</code>
	 */
	public final void setDadosBancario(DadosBancario dadosBancario) {
		this.dadosBancario = dadosBancario;
	}

}

trunk/SicaCard/src/br/com/sicacard/controller/AbastecimentoController.java
package br.com.sicacard.controller;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.model.SelectItem;

import org.apache.log4j.Logger;

import br.com.sicacard.business.AbastecimentoBusiness;
import br.com.sicacard.business.ClienteBusiness;
import br.com.sicacard.business.PostoBusiness;
import br.com.sicacard.business.impl.AbastecimentoBusinessImpl;
import br.com.sicacard.business.impl.ClienteBusinessImpl;
import br.com.sicacard.business.impl.PostoBusinessImpl;
import br.com.sicacard.model.entity.Cliente;
import br.com.sicacard.model.entity.HistoricoAbastecimento;
import br.com.sicacard.model.entity.Posto;
import br.com.sicacard.model.entity.TipoCliente;
import br.com.sicacard.model.entity.exception.BusinessException;
import br.com.sicacard.util.ApplicationConstants;

/**
 * 
 * AbastecimentoController.java
 *
 * @author Nayalison <br />
 *     		nayalison@gmail.com
 *
 * @since 06/05/2012
 * @version 1.0
 */
@ManagedBean(name = "abastecimentoController")
@ViewScoped
public class AbastecimentoController extends GenericController {

	private static final long serialVersionUID = 3765512612527298196L;
	private static final Logger LOGGER = Logger.getLogger(AbastecimentoController.class);
	private AbastecimentoBusiness business;
	private PostoBusiness postoBusiness;
	private ClienteBusiness clienteBusiness;
	private HistoricoAbastecimento historico;
	private int tipoCliente = 1;
	
	
	
	
	/**
	 * Default constructor.
	 */
	public AbastecimentoController() {
		super();
		business = new AbastecimentoBusinessImpl();
		postoBusiness = new PostoBusinessImpl();
		clienteBusiness = new ClienteBusinessImpl();
	}

	/**
	 * Get the historico
	 * @return <code>HistoricoAbastecimento</code>
	 */
	public HistoricoAbastecimento getHistorico() {
		if(historico == null) {
			historico = new HistoricoAbastecimento();
			historico.setCliente(new Cliente());
			historico.setPosto(new Posto());
		}
		return historico;
	}
	
	/**
	 * Set the historico
	 * @param historico the <code>HistoricoAbastecimento</code>
	 */
	public void setHistorico(HistoricoAbastecimento historico) {
		this.historico = historico;
	}
	
	/**
	 * Get the tipoCliente
	 * @return <code>int</code>
	 */
	public int getTipoCliente() {
		return tipoCliente;
	}

	/**
	 * Set the tipoCliente
	 * @param tipoCliente the <code>int</code>
	 */
	public void setTipoCliente(int tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	public String registar() {
		try {
			historico.setTipoCliente(TipoCliente.valueOf(tipoCliente));
			historico.setCliente(clienteBusiness.recuperarCliente(Long.valueOf(historico.getNumeroDocumento()), TipoCliente.valueOf(tipoCliente)));
			business.realizarAbastecimento(historico);
			addInfoMessage("Abastecimento registrado com sucesso");
			return ApplicationConstants.SUCCESS;
		} catch (Exception e) {
			LOGGER.error(e);
			addErrorMessage("Falha ao registrar o abastecimento");
			return ApplicationConstants.ERROR;
		}
	}
	
	public List<HistoricoAbastecimento> getLista() {
		try {
			return business.listarAbastecimentos();
		} catch (Exception e) {
			LOGGER.error(e);
			addErrorMessage("Falha ao listar os abastecimentos");
			return null;
		}
	}
	
	public List<SelectItem> getPostos() {  
	    List<SelectItem> items = new ArrayList<SelectItem>(); 
	    try {
			List<Posto> postos = postoBusiness.listar();
			for (Posto p : postos) {  
			    items.add(new SelectItem(p.getCnpj(), p.getNomeFantasia()));  
			}
		} catch (BusinessException e) {
			LOGGER.error(e);
		}  
	    return items;  
	} 

}

trunk/SicaCard/WebContent/paginas/abastecimento.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

<h:head>
	<title>Registro de abastecimento</title>
</h:head>

<ui:composition template="/template/template.xhtml">
	<ui:define name="conteudo">
		<h:outputText value="Registro de Abastecimento"></h:outputText>
		<br />
		<br />
		<h:form>
			<a4j:outputPanel id="painelPrincipal">
				<div>
					<h:outputLabel value="Tipo de Cliente" />
					<h:selectOneRadio value="#{abastecimentoController.tipoCliente}"
						required="true" >
						<f:selectItem itemValue="1" itemLabel="Pessoa Física" />
						<f:selectItem itemValue="2" itemLabel="Pessoa Jurídica" />
						<f:selectItem itemValue="3" itemLabel="Dependente" />
					</h:selectOneRadio>
				</div>
				<div>
					<h:outputLabel value="Posto" />
				    
				    <h:selectOneMenu value="#{abastecimentoController.historico.posto.cnpj}" >    
					       <f:selectItems value="#{abastecimentoController.postos}" />    
					</h:selectOneMenu> 
				</div>
				
				<div>
					<h:outputLabel value="CPF/CNPJ/CNH" />
					<h:inputText value="#{abastecimentoController.historico.numeroDocumento}"
						required="true" />
				</div>
	
				<div>
					<h:outputLabel value="Valor" />
					<h:inputText value="#{abastecimentoController.historico.valor}"
						required="true" >
						 <f:convertNumber maxFractionDigits="2"/>
					</h:inputText>
				</div>
	
				
				<div>
					<h:commandButton value="Registrar" action="#{abastecimentoController.registar}" />
				</div>
	
				<div>
					<fieldset>
						<legend>
							<h:outputLabel value="Historico de Abastecimento" />
						</legend>
	
						<rich:dataTable value="#{abastecimentoController.lista}" var="historico"
							id="table" rows="20" rowClasses="odd-row, even-row" styleClass="stable">
							<rich:column>
								<f:facet name="header">
									<h:outputText value="Posto" />
								</f:facet>
								<h:outputText value="#{historico.posto.nomeFantasia}" />
							</rich:column>
							<rich:column>
								<f:facet name="header">
									<h:outputText value="CPF/CNPJ/CNH" />
								</f:facet>
								<h:outputText value="#{historico.numeroDocumento}" />
							</rich:column>
							<rich:column>
								<f:facet name="header">
									<h:outputText value="Valor" />
								</f:facet>
								<h:outputText value="#{historico.valor}" />
							</rich:column>
						</rich:dataTable>
			
					<rich:jQuery selector=".stable tr:odd" query="addClass('odd-row')" />
					<rich:jQuery selector=".stable tr:even" query="addClass('even-row')" />
					<rich:jQuery selector=".stable tr" event="mouseover" query="jQuery(this).addClass('active-row')" />
					<rich:jQuery selector=".stable tr" event="mouseout" query="jQuery(this).removeClass('active-row')" />
					</fieldset>
	
				</div>
			</a4j:outputPanel>
		</h:form>
	</ui:define>
</ui:composition>
</html>

trunk/SicaCard/WebContent/paginas/cliente.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">

<h:head>
	<title>Cadastro de Cliente</title>
</h:head>

<ui:composition template="/template/template.xhtml">
	<ui:define name="conteudo">
		<a4j:jsFunction name="trocarTipoPessoa" action="#{clienteController.trocaTipoPessoa()}"
			render="painelPrincipal" execute="@this" />

		<h:outputText value="Cadastro de Cliente"></h:outputText>
		<br />
		<br />
		<h:form>
			<div>
				<h:selectOneRadio value="#{clienteController.flgPessoaFisica}"
					required="true" onchange="trocarTipoPessoa();">
					<f:selectItem itemValue="true" itemLabel="Pessoa Física" />
					<f:selectItem itemValue="false" itemLabel="Pessoa Jurídica" />
				</h:selectOneRadio>
			</div>
			<a4j:outputPanel id="painelPrincipal">


				<!-- Pessoa Fisica -->
				<a4j:outputPanel id="painelPessoaFisica"
					rendered="#{clienteController.flgPessoaFisica}">
					<div>
						<h:outputLabel value="CPF" />
						<h:inputText id="cpf" value="#{clienteController.clientePf.cpf}"
							required="true">
							<f:converter converterId="javax.faces.BigInteger" />
						</h:inputText>
					</div>

					<div>
						<h:outputLabel value="Nome" />
						<h:inputText value="#{clienteController.clientePf.nome}"
							required="true"  id="nome" />
					</div>
					
					<div>
						<h:outputLabel value="CNH" />
						<h:inputText value="#{clienteController.clientePf.numeroCNH}"
							required="true"  id="cnh" />
					</div>

					<div>
						<h:outputLabel value="Endereço" />
						<h:inputText value="#{clienteController.clientePf.endereco}" required="true" id="enderecoPF"/>
					</div>
					
					<div>
						<h:outputLabel value="Telefone" />
						<h:inputText value="#{clienteController.clientePf.telefone}" required="true" id="telefonePF"/>
					</div>

				</a4j:outputPanel>

				<!-- Pessoa Juridica -->
				<a4j:outputPanel id="painelPessoaJuridica"
					rendered="#{!clienteController.flgPessoaFisica}">
					<div>
						<h:outputLabel value="Nome Fantasia" />
						<h:inputText id="nomeFantasia" value="#{clienteController.clientePj.nomeFantasia}"
							required="true" />
					</div>

					<div>
						<h:outputLabel value="Razão Social" />
						<h:inputText id="razaoSocial" value="#{clienteController.clientePj.razaoSocial}"
							required="true" />
					</div>

					<div>
						<h:outputLabel value="CNPJ" />
						<h:inputText id="cnpj" value="#{clienteController.clientePj.cnpj}"
							required="true">
							<f:converter converterId="javax.faces.BigInteger" />
						</h:inputText>
					</div>
					
					<div>
						<h:outputLabel value="Endereço" />
						<h:inputText id="enderecoPJ" value="#{clienteController.clientePj.endereco}" required="true" />
					</div>
					
					<div>
						<h:outputLabel value="Telefone" />
						<h:inputText id="telefonePJ" value="#{clienteController.clientePj.telefone}" required="true" />
					</div>
					
				</a4j:outputPanel>

				<div>
					<fieldset>
						<legend>
							<h:outputLabel value="Informações Bancários" />
						</legend>

						<div>
							<h:outputLabel value="Banco" />
							<h:inputText id="banco" value="#{clienteController.dadosBancario.banco}"
								required="true" />
						</div>

						<div>
							<h:outputLabel value="Agência" />
							<h:inputText id="agencia" value="#{clienteController.dadosBancario.agencia}"
								required="true" />
						</div>

						<div>
							<h:outputLabel value="Conta" />
							<h:inputText id="conta" value="#{clienteController.dadosBancario.conta}"
								required="true" />
						</div>
					</fieldset>

				</div>

				<div>
					<fieldset>
						<legend>
							<h:outputLabel value="Dependentes" />
						</legend>

						<a4j:outputPanel id="painelDependente">
							<a4j:region>
								<div>
									<h:outputLabel value="CNH" />
									<h:inputText id="cnhDependente" value="#{clienteController.dependente.cnh}" immediate="true" >
										<f:converter converterId="javax.faces.BigInteger" />
									</h:inputText>
								</div>
	
								<div>
									<h:outputLabel value="Nome" />
									<h:inputText id="nomeDependente" value="#{clienteController.dependente.nome}" immediate="true"/>
								</div>
								
								<div>
									<a4j:commandButton value="Adicionar"
										action="#{clienteController.addDependente()}"
										render="painelDependente" />
								</div>
							</a4j:region>

							<rich:dataTable value="#{clienteController.listaDependentes}"
								var="dependente" id="table" rows="20"
								rowClasses="odd-row, even-row" styleClass="stable"
								rendered="#{not empty clienteController.listaDependentes}">
								<rich:column>
									<f:facet name="header">
										<h:outputText value="CNH" />
									</f:facet>
									<h:outputText value="#{dependente.cnh}" />
								</rich:column>
								<rich:column>
									<f:facet name="header">
										<h:outputText value="Nome" />
									</f:facet>
									<h:outputText value="#{dependente.nome}" />
								</rich:column>
								<rich:column>
									<f:facet name="header">
										<h:outputText value="Ação" />
									</f:facet>
									<a4j:region>
									<a4j:commandLink styleClass="no-decor" 
										render="painelDependente" action="#{clienteController.removeDependente(dependente)}" >
										<h:graphicImage value="/imagens/delete.gif"
											alt="deletar" />
									</a4j:commandLink>
									</a4j:region>
								</rich:column>

							</rich:dataTable>

							<rich:jQuery selector=".stable tr:odd"
								query="addClass('odd-row')" />
							<rich:jQuery selector=".stable tr:even"
								query="addClass('even-row')" />
							<rich:jQuery selector=".stable tr" event="mouseover"
								query="jQuery(this).addClass('active-row')" />
							<rich:jQuery selector=".stable tr" event="mouseout"
								query="jQuery(this).removeClass('active-row')" />

						</a4j:outputPanel>


					</fieldset>

				</div>

			</a4j:outputPanel>

			<div>
				<h:commandButton value="Salvar" action="#{clienteController.salvarCliente}" />
			</div>
		</h:form>
	</ui:define>
</ui:composition>
</html>

trunk/SicaCard/WebContent/paginas/clienteList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">


<h:head>
	<title>Listagem de Clientes</title>
</h:head>

<ui:composition template="/template/template.xhtml">
	<ui:define name="conteudo">
	<a4j:jsFunction name="trocarTipoPessoa" action="#{clienteController.trocaTipoPessoa()}"
			render="painelPrincipal" execute="@this" />
		<h:outputText value="Lista de Clientes"></h:outputText>
		<br />
		<br />
		
		<div>
		<h:form>
			<h:selectOneRadio value="#{clienteController.flgPessoaFisica}"
				required="true" onchange="trocarTipoPessoa();">
				<f:selectItem itemValue="true" itemLabel="Pessoa Física" />
				<f:selectItem itemValue="false" itemLabel="Pessoa Jurídica" />
			</h:selectOneRadio>
			
			<a4j:outputPanel id="painelPrincipal">
				<!-- Pessoa Fisica -->
				<a4j:outputPanel id="painelPessoaFisica" rendered="#{clienteController.flgPessoaFisica}">
				
					<rich:dataTable value="#{clienteController.listaClientePf}" var="cliente"
						id="tablePessoaFisica" rows="20" rowClasses="odd-row, even-row" styleClass="stable">
						<rich:column>
							<f:facet name="header">
								<h:outputText value="CPF" />
							</f:facet>
							<h:outputText value="#{cliente.cpf}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Nome" />
							</f:facet>
							<h:outputText value="#{cliente.nome}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="CNH" />
							</f:facet>
							<h:outputText value="#{cliente.numeroCNH}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Endereço " />
							</f:facet>
							<h:outputText value="#{cliente.endereco}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Telefone" />
							</f:facet>
							<h:outputText value="#{cliente.telefone}" />
						</rich:column>
					</rich:dataTable>
					
				</a4j:outputPanel>
				
				<!-- Pessoa Juridica -->
				<a4j:outputPanel id="painelPessoaJuridica" rendered="#{!clienteController.flgPessoaFisica}">
					
					<rich:dataTable value="#{clienteController.listaClientePj}" var="cliente"
						id="tablePessoaJuridica" rows="20" rowClasses="odd-row, even-row" styleClass="stable">
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Nome Fantasia" />
							</f:facet>
							<h:outputText value="#{cliente.nomeFantasia}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Razão Social" />
							</f:facet>
							<h:outputText value="#{cliente.razaoSocial}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="CNPJ" />
							</f:facet>
							<h:outputText value="#{cliente.cnpj}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Endereço " />
							</f:facet>
							<h:outputText value="#{cliente.endereco}" />
						</rich:column>
						<rich:column>
							<f:facet name="header">
								<h:outputText value="Telefone" />
							</f:facet>
							<h:outputText value="#{cliente.telefone}" />
						</rich:column>
					</rich:dataTable>
					
				</a4j:outputPanel>
				
				<rich:jQuery selector=".stable tr:odd" query="addClass('odd-row')" />
				<rich:jQuery selector=".stable tr:even" query="addClass('even-row')" />
				<rich:jQuery selector=".stable tr" event="mouseover" query="jQuery(this).addClass('active-row')" />
				<rich:jQuery selector=".stable tr" event="mouseout" query="jQuery(this).removeClass('active-row')" /> 
			</a4j:outputPanel>
	</h:form>
	</div>

	</ui:define>
</ui:composition>
</html>

trunk/SicaCard/WebContent/paginas/postoList.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich">


<h:head>
	<title>Listagem de Clientes</title>
</h:head>

<ui:composition template="/template/template.xhtml">
	<ui:define name="conteudo">
		<h:outputText value="Lista de Postos"></h:outputText>
		<br />
		<br />
		
		<h:form id="form">
			<rich:dataTable value="#{postoController.lista}" var="posto"
				id="table" rows="20" rowClasses="odd-row, even-row" styleClass="stable">
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Nome Fantasia" />
					</f:facet>
					<h:outputText value="#{posto.nomeFantasia}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Razão Social" />
					</f:facet>
					<h:outputText value="#{posto.razaoSocial}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="CNPJ" />
					</f:facet>
					<h:outputText value="#{posto.cnpj}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Telefone" />
					</f:facet>
					<h:outputText value="#{posto.telefone}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Banco " />
					</f:facet>
					<h:outputText value="#{posto.dadosBancario.banco}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Agência " />
					</f:facet>
					<h:outputText value="#{posto.dadosBancario.agencia}" />
				</rich:column>
				<rich:column>
					<f:facet name="header">
						<h:outputText value="Conta " />
					</f:facet>
					<h:outputText value="#{posto.dadosBancario.conta}" />
				</rich:column>
			</rich:dataTable>
		</h:form>

		<rich:jQuery selector=".stable tr:odd" query="addClass('odd-row')" />
		<rich:jQuery selector=".stable tr:even" query="addClass('even-row')" />
		<rich:jQuery selector=".stable tr" event="mouseover" query="jQuery(this).addClass('active-row')" />
		<rich:jQuery selector=".stable tr" event="mouseout" query="jQuery(this).removeClass('active-row')" />

	</ui:define>
</ui:composition>
</html>